useTodo hooks 구현
mywhzy/Assignment pull request #1
Opened 2024-03-18 11:55 UTC by mywhzy

2024-03-18 20:16 UTC, ndaemy requested changes
바꿔야만 하는 부분이 좀 있어서 Request changes!

2024-03-18 20:16 UTC, ndaemy commented on custom-hooks-assignment/src/pages/ItemDetailPage.tsx
> +export const ItemDetailPage = () => {
ItemDetailPage 보다는 TodoDetailPage 가 맞을듯

2024-03-18 20:16 UTC, ndaemy commented on custom-hooks-assignment/src/hooks/useTodo.ts
> +export type dataType = {
type 이 PascalCase 가 아니에요!

2024-03-18 20:16 UTC, ndaemy commented on custom-hooks-assignment/src/pages/ItemDetailPage.tsx
> +  const id = Number(useParams().id);
Number() 함수는 반환 값에 실제 숫자 뿐 아니라 NaN 도 가능하기 때문에, 해당 경우에 대해 handling 을 해줘야 할듯
지금의 경우는 useTodo 안쪽에서 처리하는게 낫겠다

2024-03-18 20:16 UTC, ndaemy commented on custom-hooks-assignment/src/hooks/useTodo.ts
> +    });
`setIsLoading(false);` 라는 코드가 겹치니까 이건 .finally() 로 빼주는게 더 코드가 이뻐질듯!

2024-03-18 20:16 UTC, ndaemy commented on custom-hooks-assignment/src/hooks/useTodo.ts
> +    axios.get(url + id)
id 가 TypeScript type 상 number 지만, NaN 도 number 타입이므로 해당 경우에 대해 handling 이 필요할듯

2024-03-18 20:16 UTC, ndaemy commented on custom-hooks-assignment/src/pages/ItemDetailPage.tsx
> +      <ItemDetail userId={data?.userId} id={data?.id} title={data?.title} completed={data?.completed} />
이렇게 optional chaining 이 많이 발생할거라면, 여기까지 왔을 때 data 가 무조건 있도록 type 을 줄여보는 것도 방법일듯해여
한 방법으로는 isLoading 을 아예 사용하지 않고 data 와 error 만을 사용하는 방법도 있고,
아니면 첫 if 문을 `if (!data || isLoading) { ... }` 같은 식으로 푸는 방법도 있답니다

2024-03-18 20:16 UTC, ndaemy commented on custom-hooks-assignment/src/pages/TodoListPage.tsx
> +  const indexes = Array.from({ length: listLength }, (_, i) => i + 1);
lodash 의 `range()` 같은 라이브러리를 사용해보는 것도 방법입니다

2024-03-18 20:16 UTC, ndaemy commented on custom-hooks-assignment/src/pages/TodoListPage.tsx
> +  const indexes = Array.from({ length: listLength }, (_, i) => i + 1);
그런데 이렇게 하드코딩하기보다는, useTodos 같은걸 만들어서 사용하는것도 방법이겠네요
왜냐하면 지금은 jsonplaceholder 를 사용하지만, 실제 서버라면 몇 개가 들었을 지 알 수 없으니까요!

2024-03-18 20:16 UTC, ndaemy commented on custom-hooks-assignment/src/hooks/useTodo.ts
> +  const [data, setData] = useState<undefined | dataType>(undefined);
undefined 는 명시적으로 쓰지 말기!

2024-03-21 11:51 UTC, mywhzy commented on custom-hooks-assignment/src/pages/TodoListPage.tsx
> +  const indexes = Array.from({ length: listLength }, (_, i) => i + 1);
그것두 좋은 방법인 거 같네요!! 저도 저런 하드코딩 방식이 맘에 들진 않았는데 내가 받아오는 todos의 개수가 얼마나 될 줄 알고 얘를 한 번에 다 받아오지?란 생각이 있어서 일부만 받아오고자 했던 이유도 있었습니다!! 페이지네이션 기능이 없는데 무작정 다 받아왔다가 무한 스크롤의 경지에 오를 거 같아서 ,, 일단 최소한의 MVP만 해보고자 30개정도만 받아오는 형태로 했었어요! 그럼 피드백 주신 부분 참고해서 전체 데이터를 받아오는 부분부터 해볼게요! 이후에 페이지네이션도 한 번 생각해보는 걸로 가보겠습니다 ☺️

2024-03-21 12:19 UTC, mywhzy commented on custom-hooks-assignment/src/hooks/useTodo.ts
> +    axios.get(url + id)
헉 이런 열림교회닫힘의 경우는,, Not A Number란 뜻을 가진애인데 어째서 type이 number!!!!!! 휴.. 좋은 정보 얻었습니다 감사합니당 🥲 
<img width="203" alt="image" src="https://github.com/mywhzy/Assignment/assets/90755664/11e0aed7-9e1d-4197-9bd1-90e653b37ecf">

2024-03-22 12:29 UTC, ndaemy commented on custom-hooks-assignment/src/hooks/useTodo.ts
> +  const url = process.env.REACT_APP_API_URL || '';
이것도 type 체크 관점에서는 좋은 방법이긴 한데, 사실 이 리액트 앱은 REACT_APP_API_URL 환경변수가 없으면 실행 자체가 말이 안되는 녀석이니까 throw 를 하거나 혹은 다른 더 좋은 방법으로 type-safe 하게 관리해주는것도 좋아여
물론 "에이 내가 저 환경변수 없이 실행시킬 일 없어~" 라면 이정도도 괜찮긴 함

2024-03-22 12:29 UTC, ndaemy commented on custom-hooks-assignment/src/hooks/useTodo.ts
> +      .finally(() => setIsLoading(false));
이건 본인 취향이긴 한데, 이 문법을 try-catch + async await 문법으로 바꿔볼 수도 있어야 합니다

2024-03-26 09:30 UTC, mywhzy commented on custom-hooks-assignment/src/pages/ItemDetailPage.tsx
> +  const id = Number(useParams().id);
useTodo내에서 파라미터로 받아온 id가 NaN인지 체크하는 로직을 추가하긴했는데 해당 라인에서도 NaN의 발생 가능성이 있다는 것이 굉장히 신경쓰이네요... 여기서도 방어로직을 해주는 편이 좋을지 투머치일지 고민입니다 !

2024-03-26 09:53 UTC, mywhzy commented on custom-hooks-assignment/src/pages/ItemDetailPage.tsx
> +      <ItemDetail userId={data?.userId} id={data?.id} title={data?.title} completed={data?.completed} />
그렇게 하면 더 직관적이면서도 명확한 코드같네요!! 안그래도 ItemDetail 컴포넌트 내부 props가 optional로 되어있는게 좋지 않았는데 수정했습니당 ^_^

2024-03-26 17:36 UTC, ndaemy approved these changes
수고하셨습니다~

2024-03-26 17:36 UTC, ndaemy commented on custom-hooks-assignment/src/utils/checkNaN.ts
> +    return new Error('NaN은 Number Type이지만 유효한 Number 값이 아닙니다.');
1. checkNaN 을 util 함수로 빼는건 괜찮은 접근이네요 👍 
2. 근데, 에러 메세지가 위와 같다면, 만약 이 에러가 터졌을 때 유저는 "난 NaN 을 보낸 적이 없는데 무슨 말이지" 같이 경험이 좋지 않을 수 있어요. 메세지를 케이스별로 특화하는게 더 좋을듯 합니다!

2024-03-26 17:36 UTC, ndaemy commented on custom-hooks-assignment/src/pages/ItemDetailPage.tsx
> +  const id = Number(useParams().id);
차라리 여기 페이지에서 id 가 NaN 일 때 "존재하지 않는 글입니다" 같은 느낌의 404 페이지를 띄워주는것도 방법일듯?
물론 서버에 반드시 요청을 보내면 좋겠다 같은 스펙이 있다면 또 다르게 처리해야겠지만!

2024-03-27 15:28 UTC, mywhzy commented on custom-hooks-assignment/src/pages/TodoListPage.tsx
> +  const indexes = Array.from({ length: listLength }, (_, i) => i + 1);
lodash 라이브러리를 이용하면 python처럼 range()를 사용할 수 있다는 걸 알게 되었네요!! 일단 외부 라이브러리 의존 없이 구현하고 싶은 마음으로 저렇게 구현한 것도 있지만 간편한 건 확실히 무시 못하군요ㅎㅎ 유용한 메소드가 많아보여서 lodash에 대해 좀 더 알아봐야할 거 같네용 감사합니닷 ㅎ

2024-03-27 15:31 UTC, mywhzy commented on custom-hooks-assignment/src/pages/TodoListPage.tsx
> +  const indexes = Array.from({ length: listLength }, (_, i) => i + 1);
useTodos hook을 만들긴했는데 url에 id가 추가된다는 거 말곤 useTodo와 내부 로직 구조가 거의 동일해보여서 함수의 사용성은 다르지만 괜히 중복 로직같단 느낌이 드네요,, 두 함수의 사용 목적이 다르다보니 분리를 하는 게 맞다고는 생각하는데 단순히 url로 데이터를 받아오는 구조 자체는 똑같아서 어떻게 해야하는지 고민입니당,, 적으면서 생각해보니 axios로 fetchdata를 하는 함수를 따로 분리해서 useTodos와 useTodo에 import해서 사용하는 방법으로 가면 어떨까 싶기도 하네요!!! 흠 🤔

2024-04-01 06:50 UTC, ndaemy requested changes
크리티컬 이슈가 하나 있어서 Request changes 걸어놓습니다!

2024-04-01 06:50 UTC, ndaemy commented on custom-hooks-assignment/src/hooks/useTodos.ts
> +  const [isLoading, setIsLoading] = useState<boolean>(true);
primitive type 의 경우 사실 generic 을 안 줘도 충분히 추론이 가능하긴 해요!

2024-04-01 06:50 UTC, ndaemy commented on custom-hooks-assignment/src/pages/TodoDetailPage.tsx
> +  if (!data || error) return <ErrorText>Error! id에 맞는 데이터를 불러올 수 없습니다.</ErrorText>;
지금은 괜찮은 코드이긴 한데, 추후 확장성 혹은 semantic 을 고려한다면 404 를 별도의 페이지로 빼는 것도 방법일듯!

2024-04-01 06:50 UTC, ndaemy commented on custom-hooks-assignment/src/pages/TodoListPage.tsx
> +  if (error) return <ErrorText>Error! 데이터를 받아오는 과정에서 Error가 발생했습니다.</ErrorText>;
TodoDetailPage 에서는 잘했는데, 여기선 이렇게 되면 에러가 뜰 일이 없어요. 
error 가 있는 경우에 세 가지 state 는 각각 
```typescript
data === null // true
isLoading === false // true
typeof error === 'object' // true
```
일텐데, 그렇다면 !data 조건에 먼저 걸려서 에러가 있더라도 "로딩 중..." 이 뜨게 될거에요

2024-04-01 10:41 UTC, mywhzy commented on custom-hooks-assignment/src/hooks/useTodos.ts
> +  const [isLoading, setIsLoading] = useState<boolean>(true);
TypeScript를 사용한다면 좀 더 명시적인 코드를 작성해야되지 않을까 싶은 마음에 적은거긴한데ㅎㅎ.. 추론이 가능한 경우엔 생략해도 괜찮은걸까요?? 이왕이면 조금 더 좋은, 올바른 코드를 작성하는 방식을 배우고 싶은지라 필요한 경우와 생략해도 되는 경우에 대해 항상 고민하게 되네요ㅜㅅㅜ

2024-04-01 10:42 UTC, mywhzy commented on custom-hooks-assignment/src/pages/TodoDetailPage.tsx
> +  if (!data || error) return <ErrorText>Error! id에 맞는 데이터를 불러올 수 없습니다.</ErrorText>;
저도 생각해보니까 에러박스를 컴포넌트로 분리할 바엔 차라리 Error Page로 렌더링하는게 더 좋은 방식이라고 느껴지네용ㅎㅎ 반영해보겠습니다 !!!

2024-04-02 12:07 UTC, rninzi commented on custom-hooks-assignment/src/pages/TodoListPage.tsx
> +  if (error) return <ErrorText>Error! 데이터를 받아오는 과정에서 Error가 발생했습니다.</ErrorText>;
세상에 그렇구나... 조건문 쓰기 전에 분명 각 case에 대해 체크했던 거 같은데 이런 큰 실수를... 바로 고쳐볼게요 좋은 지적 감사합니닷,,

2024-04-02 12:15 UTC, mywhzy commented on custom-hooks-assignment/src/hooks/useTodo.ts
> +  const url = process.env.REACT_APP_API_URL || '';
저도 `이 리액트 앱은 REACT_APP_API_URL 환경변수가 없으면 실행 자체가 말이 안되는 녀석` 요거에 왕 공감합니닷... 얘가 없을 때를 대비한 error에 대해서라도 처리를 해주는 게 맞는 거 같네요! 공개된 api 주소긴 하지만 나름 api fetching을 하는 거라 url을 비공개로 처리하고 싶었는데 흠... 🤔
이 경우에는 없으면 그냥 원본 url을 까는게 나을까 싶지만 보통의 api 연결 url은 private하게 관리해야되니까 최대한 평소에도 환경변수를 통해 관리하고 싶은 맘이 있어용 어떤 방식으로 수정하는게 좋은 방법일쥐...

2024-04-02 12:58 UTC, mywhzy commented on custom-hooks-assignment/src/pages/ItemDetailPage.tsx
> +  const id = Number(useParams().id);
`if (Number.isNaN(id) || !data || error) return <NotFoundPage />;`
요런식으로여???? 아니다 일케 해도 useTodo에 id가 이미 전달된 후겠지...? 흠냐링

2024-04-03 07:03 UTC, ndaemy commented on custom-hooks-assignment/src/hooks/useTodos.ts
> +  const [isLoading, setIsLoading] = useState<boolean>(true);
생략했을 때 생략을 안했을 때랑 아무 차이가 없으면 생략해도 됩니다
그러라고 자동 추론이 있는거니까요!

2024-04-03 07:07 UTC, ndaemy approved these changes
굿 아주 수고하셨습니다~

2024-04-03 07:07 UTC, ndaemy commented on custom-hooks-assignment/src/pages/NotFoundPage.tsx
잘 했는데.. 왜 4 space 랑 2 space 가 섞여있는거죠..?

2024-04-03 07:07 UTC, ndaemy commented on custom-hooks-assignment/src/pages/NotFoundPage.tsx
> +    margin: 10px 0 5px 0;
알고 있겠지만 요건 아래처럼 shortened 될 수 있어요 참고우
```suggestion
    margin: 10px 0 5px;
```

2024-04-03 11:02 UTC, mywhzy commented on custom-hooks-assignment/src/pages/NotFoundPage.tsx
이거는,, 왠지 return문 뒤에 소괄호 이후에 줄바꿈을 안 해서 그런 거 같은데 webstorm 자체에 code style 세팅때문에 그런가봐여... return 문 이후에 줄바꿈 하는 거 적용법 찾다가 그냥 앞으로는 초반에 항상 프리티어 세팅해두고 쓰기로 했답니다 ^^*...

2024-04-03 11:04 UTC, mywhzy commented on custom-hooks-assignment/src/pages/NotFoundPage.tsx
> +    margin: 10px 0 5px 0;
맞다 !!!!!!!!!!! 간만에 복습 겸 다시 메모해야지 margin:상하좌우 / margin: 상 우 하 좌 / margin: 상하 좌우 / margin: 상 좌우 하 !!!!! 3분할도 됨!!!!!!!!!!!! ✍🏻

2024-04-04 07:00 UTC, ndaemy commented on custom-hooks-assignment/src/pages/ItemDetailPage.tsx
> +  const id = Number(useParams().id);
엥 에러가 있으면 NotFound 가 아니라 에러 모달같은걸 보여줘야 하는거 아닐까..?

2024-04-04 07:01 UTC, ndaemy commented on custom-hooks-assignment/src/pages/TodoListPage.tsx
> +  const indexes = Array.from({ length: listLength }, (_, i) => i + 1);
주소가 아예 달라서 + useSWR 이 키를 기준으로 캐싱을 해서 중복같지만 줄일 방법은 딱히 없을거에여
비즈니스 로직이 있다면 좀 줄일 부분이 있을텐데 지금은 딱히 그것도 아니라서!

2024-04-04 07:05 UTC, ndaemy commented on custom-hooks-assignment/src/hooks/useTodo.ts
> +  const url = process.env.REACT_APP_API_URL || '';
뭐 간단하게는 아래같은 방법이 있을듯?
```typescript
  if (!process.env.REACT_APP_API_URL) {
    throw new Error('없으면 안됨');
  }
```

2024-04-04 07:06 UTC, ndaemy commented on custom-hooks-assignment/src/pages/NotFoundPage.tsx
그게 맞져 ㅋㅋㅋㅋ

2024-04-27 12:32 UTC, merged